[workspace]
members = ["dev/crates/*"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
track-config = { path = "dev/crates/track-config" }
